@echo off
setlocal DisableDelayedExpansion
set "CRM_LAUNCH_ROOT=%~dp0"
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; try { $crmUrl='http://127.0.0.1:4318'; $crmProbe=[System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback,4318); $crmOccupied=$false; try { $crmProbe.Start() } catch { $crmOccupied=$true } finally { $crmProbe.Stop() }; if ($crmOccupied) { Add-Type -AssemblyName System.Net.Http; $crmHandler=[System.Net.Http.HttpClientHandler]::new(); $crmHandler.AllowAutoRedirect=$false; $crmHandler.UseProxy=$false; $crmClient=[System.Net.Http.HttpClient]::new($crmHandler); $crmClient.Timeout=[TimeSpan]::FromSeconds(2); $crmResponse=$null; try { $crmResponse=$crmClient.GetAsync($crmUrl+'/api/visao').GetAwaiter().GetResult(); if ([int]$crmResponse.StatusCode -ne 200) { throw 'Resposta local indisponivel.' }; $crmBody=$crmResponse.Content.ReadAsStringAsync().GetAwaiter().GetResult(); if (!$crmBody.TrimStart().StartsWith('{')) { throw 'Resposta local invalida.' }; $crmView=ConvertFrom-Json -InputObject $crmBody; $crmSchema=$crmView.schemaVersion; if (!(($crmSchema -is [int] -or $crmSchema -is [long] -or $crmSchema -is [double] -or $crmSchema -is [decimal]) -and $crmSchema -eq 1)) { throw 'Resposta local incompativel.' } } finally { if ($crmResponse) { $crmResponse.Dispose() }; $crmClient.Dispose() }; Start-Process $crmUrl; Write-Host 'CRM aberto no navegador.'; exit 0 }; $crmNode=$env:CRM_NODE_PATH; if ([string]::IsNullOrWhiteSpace($crmNode)) { $crmNode=(Get-Command node.exe -CommandType Application -ErrorAction Stop | Select-Object -First 1).Source }; $crmSession = & (Join-Path $env:CRM_LAUNCH_ROOT 'Iniciar CRM.ps1') -NodePath $crmNode; Start-Process $crmSession.url; Write-Host 'CRM aberto no navegador.'; Write-Host ('Para encerrar o servidor: '+$crmSession.encerrar) } catch { Write-Host 'Nao foi possivel abrir o CRM. Confira se o Node esta configurado e se a porta 4318 esta livre.'; exit 1 }"
if errorlevel 1 (
  pause
  exit /b 1
)
endlocal
exit /b 0
