const {test}=require('node:test');
const assert=require('node:assert/strict');
const {spawnSync,spawn}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const {capturaValida,temporario,redefinirHorario,mudarCelula}=require('./fixtures.cjs');
const {lerEstado,promoverCaptura}=require('../src/snapshot.cjs');
const cli=path.resolve(__dirname,'../scripts/importar-captura.cjs');
function executar(args) {
  if (!fs.existsSync(cli)) return spawnSync(process.execPath,['-e',"process.stderr.write('CLI ainda não implementado'); process.exitCode=70;"],{encoding:'utf8'});
  return spawnSync(process.execPath,[cli,...args],{encoding:'utf8'});
}

test('C-fase8-preflight identidade sensível dá exit 1 sem substituir captura válida',t=>{
  const dir=temporario(t),data=path.join(dir,'dados'),input=path.join(dir,'entrada.json'),vigente=capturaValida();
  fs.writeFileSync(input,JSON.stringify(vigente));
  assert.equal(executar([input,'--data-dir',data]).status,0);
  const candidata=capturaValida();candidata.capturaId='captura-cli-preflight-recusada';
  redefinirHorario(candidata,'2026-10-02T12:01:00Z','2026-10-02T12:06:00Z');
  const sensivel='ghp_'+'identificador-ficticio-'.repeat(2);
  mudarCelula(candidata,'Páginas',1,'arquivo_imagem_id',sensivel);
  fs.writeFileSync(input,JSON.stringify(candidata));
  const result=executar([input,'--data-dir',data]);
  assert.equal(result.status,1);assert.equal(result.stdout,'');
  assert.match(result.stderr,/Páginas.*arquivo_imagem_id.*sensível/);
  assert.ok(!result.stderr.includes(sensivel) && !result.stderr.includes(dir));
  const state=lerEstado(data);
  assert.equal(state.captura.envelope.capturaId,vigente.capturaId);
  assert.equal(state.captura.envelope.completedAt,vigente.completedAt);
  assert.equal(state.ultimaTentativa.resultado,'falhou');
  assert.equal(state.historico.length,2);
});
test('C01 argumento ausente e URL são recusados antes de qualquer I/O', t => {
  const dir=temporario(t);
  for (const args of [[],['https://exemplo.invalid/captura'],['arquivo','--opcao-inesperada'],['arquivo','--data-dir']]) {
    const r=executar([...args,'--data-dir',dir]);
    assert.notEqual(r.status,0);
    assert.match(r.stderr,/caminho local|argument/);
    assert.equal(r.stdout,'');
    assert.deepEqual(fs.readdirSync(dir),[]);
  }
});
test('C02 arquivo ausente e JSON inválido não despejam células ou caminho', t => {
  const dir=temporario(t), input=path.join(dir,'entrada.json'), data=path.join(dir,'dados');
  const missing=executar([input,'--data-dir',data]);
  assert.notEqual(missing.status,0);
  assert.match(missing.stderr,/arquivo local/);
  fs.writeFileSync(input,'{"texto":"sentinela-nao-publicar"');
  const invalid=executar([input,'--data-dir',data]);
  assert.notEqual(invalid.status,0);
  assert.match(invalid.stderr,/JSON/);
  assert.doesNotMatch(invalid.stderr,/sentinela-nao-publicar/);
  assert.ok(!invalid.stderr.includes(dir));
});
test('C03 CLI real promove, repete sem duplicar e rejeita parcial/conflito', t => {
  const dir=temporario(t), input=path.join(dir,'entrada.json'), data=path.join(dir,'dados'), raw=capturaValida();
  fs.writeFileSync(input,JSON.stringify(raw));
  const accepted=executar([input,'--data-dir',data]);
  assert.equal(accepted.status,0);
  assert.match(accepted.stdout,/captura-sintetica-01.*completa/);
  assert.doesNotMatch(accepted.stdout,/sentinela-nao-publicar|fonte-sintetica/);
  const before=fs.readFileSync(path.join(data,'atual.json'),'utf8');
  assert.match(executar([input,'--data-dir',data]).stdout,/sem_alteracao/);
  assert.equal(fs.readFileSync(path.join(data,'atual.json'),'utf8'),before);
  raw.spreadsheetId='fonte-diferente-sintetica';
  fs.writeFileSync(input,JSON.stringify(raw));
  const conflict=executar([input,'--data-dir',data]);
  assert.notEqual(conflict.status,0);
  assert.match(conflict.stderr,/conflito/);
  assert.equal(lerEstado(data).historico.length,2);
  raw.capturaId='captura-incompleta'; raw.tables.Cenas.complete=false;
  fs.writeFileSync(input,JSON.stringify(raw));
  assert.notEqual(executar([input,'--data-dir',data]).status,0);
  assert.equal(lerEstado(data).captura.envelope.capturaId,'captura-sintetica-01');
});
test('C04 arquivo ausente confirma falha sem inventar captura nem expor caminho', t => {
  const dir=temporario(t), data=path.join(dir,'dados'), input=path.join(dir,'ausente.json');
  const result=executar([input,'--data-dir',data]);
  assert.equal(result.status,1);
  const state=lerEstado(data);
  assert.equal(state.captura,null);
  assert.equal(state.historico.length,1);
  assert.equal(state.ultimaTentativa.resultado,'falhou');
  assert.equal(state.ultimaTentativa.capturaId,null);
  assert.match(state.ultimaTentativa.motivoResumo,/arquivo local ausente ou ilegível/);
  assert.ok(!JSON.stringify(state).includes(dir));
});
test('C04 JSON quebrado confirma falha e preserva bytes e horário da última válida', t => {
  const dir=temporario(t), data=path.join(dir,'dados'), input=path.join(dir,'entrada.json'), raw=capturaValida();
  fs.writeFileSync(input,JSON.stringify(raw));
  assert.equal(executar([input,'--data-dir',data]).status,0);
  const capture=path.join(data,'capturas',raw.capturaId+'.json'), before=fs.readFileSync(capture);
  fs.writeFileSync(input,'{"texto":"sentinela-nao-publicar"');
  const result=executar([input,'--data-dir',data]);
  assert.equal(result.status,1);
  const state=lerEstado(data);
  assert.equal(state.historico.length,2);
  assert.equal(state.ultimaTentativa.resultado,'falhou');
  assert.equal(state.ultimaTentativa.capturaId,null);
  assert.match(state.ultimaTentativa.motivoResumo,/JSON inválido no arquivo local/);
  assert.equal(state.captura.envelope.completedAt,raw.completedAt);
  assert.deepEqual(fs.readFileSync(capture),before);
  assert.doesNotMatch(result.stderr+JSON.stringify(state.historico),/sentinela-nao-publicar/);
  assert.ok(!JSON.stringify(state.historico).includes(dir));
});
test('C04 armazenamento indisponível informa que a falha de entrada não foi registrada', t => {
  const dir=temporario(t), data=path.join(dir,'dados'), input=path.join(dir,'ausente.json');
  fs.writeFileSync(data,'obstáculo sintético');
  const result=executar([input,'--data-dir',data]);
  assert.equal(result.status,1);
  assert.match(result.stderr,/persistência: falha não pôde ser registrada/);
  assert.ok(!result.stderr.includes(dir));
});
test('C05 duas instâncias reais não perdem recibos nem fazem rollback da captura', async t => {
  const dir=temporario(t), data=path.join(dir,'dados'), raw=capturaValida();
  promoverCaptura(raw,data);
  const inputA=path.join(dir,'a.json'), inputB=path.join(dir,'b.json');
  const a=structuredClone(raw),b=structuredClone(raw);
  a.capturaId='captura-a';b.capturaId='captura-b';
  redefinirHorario(a,'2026-10-02T12:01:00Z','2026-10-02T12:06:00Z');
  redefinirHorario(b,'2026-10-02T12:02:00Z','2026-10-02T12:07:00Z');
  fs.writeFileSync(inputA,JSON.stringify(a));
  fs.writeFileSync(inputB,JSON.stringify(b));
  const marker=path.join(dir,'barreira'), release=path.join(dir,'continuar');
  const snapshot=path.resolve(__dirname,'../src/snapshot.cjs');
  const code="const fs=require('node:fs'),path=require('node:path');const [module,input,data,marker,release]=process.argv.slice(1);const rename=fs.renameSync;fs.renameSync=(a,b)=>{if(b===path.join(data,'atual.json')){fs.writeFileSync(marker,'pronto');while(!fs.existsSync(release))Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10);}return rename(a,b);};const result=require(module).promoverCaptura(JSON.parse(fs.readFileSync(input,'utf8')),data);process.exitCode=result.resultado==='completa'?0:1;";
  const first=spawn(process.execPath,['-e',code,snapshot,inputA,data,marker,release],{stdio:'ignore'});
  t.after(()=>{if(first.exitCode===null)first.kill();});
  const finished=new Promise((resolve,reject)=>{first.once('error',reject);first.once('exit',resolve);});
  const until=Date.now()+5000;
  while (!fs.existsSync(marker) && Date.now()<until && first.exitCode===null) await new Promise(resolve=>setTimeout(resolve,10));
  assert.ok(fs.existsSync(marker),'primeira instância chegou antes de confirmar');
  const second=executar([inputB,'--data-dir',data]);
  const invalid=path.join(dir,'quebrado.json');
  fs.writeFileSync(invalid,'{"semFim":');
  const failed=executar([invalid,'--data-dir',data]);
  fs.writeFileSync(release,'continuar');
  assert.equal(await finished,0);
  assert.equal(second.status,1);
  assert.match(second.stderr,/importação em andamento/);
  assert.equal(failed.status,1);
  assert.match(failed.stderr,/importação em andamento/);
  const state=lerEstado(data);
  assert.equal(state.captura.envelope.capturaId,'captura-a');
  assert.deepEqual(state.historico.map(r=>r.capturaId),[raw.capturaId,'captura-a']);
  assert.equal(executar([inputB,'--data-dir',data]).status,0);
  assert.deepEqual(lerEstado(data).historico.map(r=>r.capturaId),[raw.capturaId,'captura-a','captura-b']);
});
